name: Test & Deploy
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # Test part
    - name: â˜‘ï¸ Checkout code
      uses: actions/checkout@v2

    - name: ðŸ’Ž Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        #ruby-version: 2.7 # Not necessary if `.ruby-version` is given

    - name: ðŸ‘¤ Get commit info for notification
      run: |
        echo "COMMIT_ACTOR_NAME=${{ github.actor }}" | awk -F '-preview' '{print $1}' >> $GITHUB_ENV
        echo "COMMIT_SHORT_SHA=`git rev-parse --short=8 ${{ github.sha }}`"           >> $GITHUB_ENV
        echo "COMMIT_MESSAGE=`git log --format=%B -n 1 ${{ github.event.after }}`"    >> $GITHUB_ENV

    # NOTE: jekyll-action-ts below include this step
    #- name: ðŸ§ª Install gems
    #  run: |
    #    bundle config set with 'test'
    #    bundle config set path 'vendor/bundle'
    #    bundle install --jobs 4 --retry 3

    # https://github.com/limjh16/jekyll-action-ts
    - name: ðŸ”¨ Build files with optimization
      uses: limjh16/jekyll-action-ts@v2
      with:
        ### Enables caching. Similar to https://github.com/actions/cache.
        enable_cache: true

        ### Uses prettier https://prettier.io to format jekyll output HTML.
        #format_output: true

        ### Sets prettier options (in JSON) to format output HTML. For example, output tabs over spaces.
        ### Possible options are outlined in https://prettier.io/docs/en/options.html
        # prettier_opts: '{ "useTabs": true }'

    - name: ðŸ‘€ Test files
      run: |
        bundle exec rake test SKIP_BUILD=true
        bundle exec jekyll doctor

    - name: ðŸ†– Notify results (Failed)
      if:   github.repository_owner == 'mitou' && failure()
      uses: mahaker/actions-idobata@v1.1.1
      with:
        hookUrl: ${{ secrets.IDOBATA_GITHUB_ACTIONS }}
        format: 'html'
        message: |
          <div>
          CI build for <a href='https://github.com/${{ github.repository }}'>${{ github.repository }}</a> : <span class='label label-danger'>Failure</span> (<a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>GitHub Actions</a>)<br>
          <img src='https://github.com/${{ env.COMMIT_ACTOR_NAME }}.png' class='icon-rounded' width='16' height='16'> <a href='https://github.com/${{ env.COMMIT_ACTOR_NAME }}'>${{ env.COMMIT_ACTOR_NAME }}</a>: ${{ env.COMMIT_MESSAGE }} (<a href='https://github.com/${{ github.repository }}/commit/${{ github.sha }}'>${{ env.COMMIT_SHORT_SHA }}</a>)
          </div>

    - name: ðŸ†— Notify results (Success)
      if:   github.repository_owner == 'mitou' && success()
      uses: mahaker/actions-idobata@v1.1.1
      with:
        hookUrl: ${{ secrets.IDOBATA_GITHUB_ACTIONS }}
        format: 'html'
        message: |
          <div>
          CI build for <a href='https://github.com/${{ github.repository }}'>${{ github.repository }}</a> : <span class='label label-success'>Success</span> (<a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>GitHub Actions</a>)<br>
          <img src='https://github.com/${{ env.COMMIT_ACTOR_NAME }}.png' class='icon-rounded' width='16' height='16'> <a href='https://github.com/${{ env.COMMIT_ACTOR_NAME }}'>${{ env.COMMIT_ACTOR_NAME }}</a>: ${{ env.COMMIT_MESSAGE }} (<a href='https://github.com/${{ github.repository }}/commit/${{ github.sha }}'>${{ env.COMMIT_SHORT_SHA }}</a>)
          </div>

    # Deploy part
    - name: ðŸš€ Deploy to GitHub Pages (WIP)
      if:   github.ref == 'refs/heads/master' && job.status == 'success'
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir:    ./_site
